### ISSUE TITLE
GitHub Actions CI/CD Pipeline

### ISSUE THREAD

**Issue by wkhabou3** [YixiongHao/spotify-wrapper#5]
### User Story 9 (and 9b)

As a developer, I would like a GitHub Actions CI/CD pipeline to verify that my
changes build and are formatted correctly (according to pylint or pep8) and to
prevent PRs with bad changes from being merged into main

9b. ...as well as integrating code coverage libraries into the CI pipeline that
prevent the merging of PRs with less than 80% code coverage

**Criteria:**

a. 2 points
b. +5 points for integrating code coverage libraries into the CI pipeline that
prevent the merging of PRs with less than 80% code coverage
i. Tip: We highly recommend starting this user story early and iteratively
adding new unit tests with each new PR
ii. Note: your codebase must meet or exceed this coverage goal during
demo time to qualify. Your unit tests must also be non-trivial, as we
will not accept purposeless tests.

**Comment by yuvrajdhadwal** [comment]
Started work towards this today, however i am not able to set up the conda environment to ensure all dependencies are saved. will continue working on this user story with a different approach in the future

**Comment by yuvrajdhadwal** [comment]
should be done when yixiong updates repo settings
